spring:
  application:
    name: xinguan-base-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xinguan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: 123456
    username: root

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8082

# 老版本使用mybatis-plus
# 新版本直接mybatis
mybatis:
  configuration:
    # 控制台日志打印
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除的实体字段名
      logic-delete-value: 1     #逻辑已删除值（默认为1）
      logic-not-delete-value: 0 #逻辑未删除值（默认为0）
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.forward.system.entity
